# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.5

# Site settings
# Site settings
title:              The Modern Hypatia
logo:               # Logo image URL
description:        Thoughts, Stories and Ideas on Science for Women
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://themodernhypatia.com/' # The base hostname & protocol for your site
twitter:            
facebook:           
instagram:          

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

plugins:
  - jekyll-paginate

include:
  - _pages

exclude:
  - vendor
  - _pages/style-guide.md
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         topic
tag_page_layout:      tag_page
tag_permalink_style:  pretty



# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  xenia:
    name: Xènia Pérez Sitjà
    bio: Renegade scientist, artist and leader     
    gravatar: https://en.gravatar.com/xeniapsitja
    email:    
    website: 
    github:   
    twitter:
  alicia:
    name: Alicia Molinero Pérez
    bio: Neuroscientist and writer
    gravatar:
    email:
    website:
    github:
    twitter: